spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Provide routes to other services here
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: Retry
              args:
                retries: 3
        - id: message
          uri: lb://MESSAGE
          predicates:
            - Path=/api/v1/message/**
          filters:
            - name: Retry
              args:
                retries: 3

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true